use_frameworks!

target 'UnicodeEastAsianWidth_Example' do
  pod 'EastAsianWidth', :path => '../'

  target 'UnicodeEastAsianWidth_Tests' do
    inherit! :search_paths

    pod 'Quick' 
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
