# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4.1
language: swift
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/UnicodeEastAsianWidth.xcworkspace -scheme UnicodeEastAsianWidth-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
